spring:
  main:
    allow-circular-references: true

  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false

  data:
    mongodb:
      host: localhost
      port: 0
      database: SpringBatchExampleDB

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.example.springbatch.chandgelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

app:
  ages-count-to-add: 1
  input-file: entries.csv
  output-file: output.dat

#debug: true
