server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    url: jdbc:postgresql://localhost:5430/demoDB
    user: usr
    password: pwd


logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
