server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans

application:
  message: "Test Props msg@@@"
  locale: ru_RU

messager:
  message: "Hello from Messager test"