spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: awesomeMongo

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.example.mongodbdemo.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: ERROR